version: '3'

services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: pf1234
      MYSQL_USER: caio
      MYSQL_PASSWORD: pf1234
      MYSQL_DATABASE: python_full
    ports:
      - "3308:3306"
    networks:
      - django-rede

  web:
    build: .
    environment:
      NAME_DB: python_full
      USER_DB: caio
      PASSWORD_DB: pf1234
      HOST_DB: db
      PORT_DB: 3306
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dockerizando
    ports:
      - 8000:8000
    depends_on: 
      - db
    networks:
      - django-rede

networks:
  django-rede:
    driver: bridge